[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"

[MPIPreferences]
__clear__ = ["libmpi", "abi", "mpiexec", "cclibs", "preloads_env_switch"]
_format = "1.0"
binary = "OpenMPI_jll"
preloads = []

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
